### PR TITLE
build and publish to pypi

### PR DESCRIPTION
**Pull request by moonso**
# Summary

- This pr adds a workflow to automaticalli publish new releases to PyPI
- It also modifies setup.py tp remove unused code

## This

There has not been releases published to pypi in a long time. When housekeeper is moved out from the production environment to it's own environment we will be able to just `pip install -U housekeeper`.

## Testing

No testing required

### Expected outcome
- [ ] New build is published to pypi
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by @barrystokman 
- [x] "Merge and deploy" approved by MM
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by barrystokman — APPROVED** [review]
:package:

**Comment by moonso** [comment]
Thank @barrystokman , what do you think @Mropat ?

**Review by Mropat — APPROVED** [review]
:+1:

**Comment by moonso** [comment]
Skärmavbild 2020-09-07 kl  15 56 39

🍰 🥳

**Pull request merged**
