### PR TITLE
Fixes add and delete commands

### PR DESCRIPTION
**Pull request by moonso**
This PR adds fixes a bug when running housekeeper `add` and `delete` commands

**How to prepare for test**:
- [x] ssh to hasta (depending on type of change)
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-housekeeper-stage.sh [THIS-BRANCH-NAME]`
- [x] activate stage: `us`

**How to test**:

- [x] run following command: `housekeeper add file --help`

**Expected outcome**:
- [x] There is no error message
- [x] Take a screenshot and attach or copy/paste the output.

Skärmavbild 2020-05-08 kl  09 37 36

**Review:**
- [x] code approved by  @barrystokman 
- [x] tests executed by @moonso 
- [x] "Merge and deploy" approved by @moonso 
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by moonso** [comment]
This is a hot fix, could someone have a look @barrystokman , @henrikstranneheim , @patrikgrenfeldt

**Comment by moonso** [comment]
Thanks @barrystokman

**Comment by moonso** [comment]
Skärmavbild 2020-05-08 kl  10 01 03

**Comment by henrikstranneheim** [comment]
NIce! Well done!

**Comment by henrikstranneheim** [comment]
I will add it to the back-log as done- together with the other HK PRs, so you bring the rest of us up to speed on the great changes. Great work

**Pull request merged**
