### PR TITLE
Remove bundles [WIP]

### PR DESCRIPTION
**Pull request by ingkebil**
This PR makes sure when one removes a bundle, it also removes all versions of that bundle.

How to test:

Expected outcome:

This is a minor version as we are changing existing functionality in a backwards compatible manner.

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
Could you add the description for this PR?

**Comment by ingkebil** [comment]
Sorry about the emails! This is an old PR and merging master into this branch triggered a code review request. It is still a work in progress and I'll let you know when this is ready :)

**Comment by ingkebil** [comment]
Oh nice, Barry. You wrote this! :)

**Comment by ingkebil** [comment]
Recreate the HK CLI instead so that all adds should have a delete. Reuse code there.

**Pull request closed without merging**
