### PR TITLE
fix(python): Syntax warning

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### Added

-

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] ssh to Hasta
- [ ] Test your branch with

```bash
housekeeper-test-deploy fix-python-syntax-warning
housekeeper-test get bundle justhusky
```
Any migrations need to be applied manually with alembic against the stage database.

### How to test
- [ ] login to ...
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
### Removed Syntaxwarning, 👍 
```
enrik.stranneheim@hasta:~] [base] $ housekeeper-test get bundle justhusky
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:6533c3eba3f3cd4c840877f9245b26929fc8c22a39f42c872aa314c32c6d654b
Skipping fetch of repeat blob sha256:6671afbf80d520b90e6bc20b00bf42d8c8b9b03f37e60a0bdb47ee01564df8b7
Skipping fetch of repeat blob sha256:035d07709dfb5588e1576091d0f994ee2c7ec39e89150803ff8ef975a9034596
Skipping fetch of repeat blob sha256:102a6e7f7a21934a56851632b76315e0c2067b22256a4543c859a1c561bd957b
Skipping fetch of repeat blob sha256:e49ef8976f018af3a4a1ccada0d4f8c2ec51f9d2f07963ee3639f39515352df0
Skipping fetch of repeat blob sha256:707845890a326417b9e14b4285012cd65ee22bb59fc16830291fbfcc494c1899
Skipping fetch of repeat blob sha256:67d2b6235a489b8afa7ffaaa77d0f3fcabaddaee57edf63de84f244e6a2950c6
Copying config sha256:d0589e16af378184e29793d6771308a9a5d7481bff540338a2150da521a7e201
 5.84 KiB / 5.84 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: /home/henrik.stranneheim/.singularity/cache/oci-tmp/ff8befeb8401b19656043038269816f66ae2a084f9bca89fdbcc78ade5b43c4d/housekeeper_fix-python-syntax-warning.sif
INFO:    Image cached as SIF at /home/henrik.stranneheim/.singularity/cache/oci-tmp/ff8befeb8401b19656043038269816f66ae2a084f9bca89fdbcc78ade5b43c4d/housekeeper_fix-python-syntax-warning.sif
2024-09-25 09:29:43 hasta.scilifelab.se housekeeper.cli.core[122607] INFO Use root path /home/proj/stage/housekeeper-bundles
                                              📦 Bundle table 📦
┏━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ ID   ┃ Bundle name ┃ Version IDs                                                               ┃ Created    ┃
┡━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ 8925 │ justhusky   │ 191243, 178836, 167748, 140963, 136933, 120104, 51171, 42582, 16939, 9523 │ 2019-06-11 │
└──────┴─────────────┴───────────────────────────────────────────────────────────────────────────┴────────────┘
                               📕 Version table 📕
┏━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━┓
┃ ID     ┃ Bundle name ┃ Nr files ┃ Included   ┃ Archived ┃ Created    ┃ Expires ┃
┡━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━┩
│ 191243 │ justhusky   │ 356      │ 2024-06-25 │          │ 2024-06-24 │         │
└────────┴─────────────┴──────────┴────────────┴──────────┴────────────┴─────────┘
                                                                                                 📜 Local files 📜
┏━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ID      ┃ File name                                                                                                                                       ┃ Tags                                                ┃
┡━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 6273863 │ /home/proj/stage/housekeeper-bundles/justhusky/2024-06-24/earlycasualcaiman_lanes_1_fastp_sorted_md.cram                                        │ earlycasualcaiman, cram, scout                      │
│ 6273864

**Comment by henrikstranneheim** [comment]
This fixes the syntaxwarning without changing the regexp, hence no worse than before. The regexp and use of it looks complex to change, but it looks like the Sonarcloud warning is not relevant.

**Review by diitaz93 — APPROVED** [review]
💯

**Comment by henrikstranneheim** [comment]
Deployed to prod

**Pull request merged**
