### PR TITLE
Upgrade to Python 3.8

### PR DESCRIPTION
**Pull request by seallard**
## Description
All the packages support Python 3.8. The tests pass when run with Python 3.8.

### Fixed
- Upgrade to Python 3.8

This [version](https://semver.org/) is a:
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by diitaz93 — APPROVED** [review]
👍

**Comment by seallard** [comment]
Upgrade stage to Python 3.8 in https://github.com/Clinical-Genomics/cg/pull/2557

Deploying this branch:
```
θ65° [sebastian.allard@hasta:~] [S_base] 5s $ bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t housekeeper -b upgrade-python
Collecting git+https://github.com/Clinical-Genomics/housekeeper@upgrade-python
  Running command git clone --quiet https://github.com/Clinical-Genomics/housekeeper /home/sebastian.allard/tmp/pip-req-build-a_1bxig6
  Cloning https://github.com/Clinical-Genomics/housekeeper (to revision upgrade-python) to ./tmp/pip-req-build-a_1bxig6
  Running command git checkout -b upgrade-python --track origin/upgrade-python
  Resolved https://github.com/Clinical-Genomics/housekeeper to commit 8045080257d306e3e7e2bb9d9692297156b17e1c
  Switched to a new branch 'upgrade-python'
  Installing build dependencies: started
  Branch upgrade-python set up to track remote branch upgrade-python from origin.
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: housekeeper
  Building wheel for housekeeper (pyproject.toml): started
  Building wheel for housekeeper (pyproject.toml): finished with status 'done'
  Created wheel for housekeeper: filename=housekeeper-4.8.5-py2.py3-none-any.whl size=31918 sha256=bc5dd6b259e80d940302939692bdeb1a6af256823c7ca6235bbb4633aacdacd7
  Stored in directory: /home/sebastian.allard/tmp/pip-ephem-wheel-cache-8gdrx_2m/wheels/41/2e/37/5c7dfb127599311dc1bc94ba5263f0731e97062a5e9b1e49ba
Successfully built housekeeper
Installing collected packages: housekeeper
  Attempting uninstall: housekeeper
    Found existing installation: housekeeper 4.8.5
    Uninstalling housekeeper-4.8.5:
      Successfully uninstalled housekeeper-4.8.5
Successfully installed housekeeper-4.8.5
Collecting git+https://github.com/Clinical-Genomics/housekeeper@upgrade-python
  Running command git clone --quiet https://github.com/Clinical-Genomics/housekeeper /home/sebastian.allard/tmp/pip-req-build-npzov33p
  Cloning https://github.com/Clinical-Genomics/housekeeper (to revision upgrade-python) to ./tmp/pip-req-build-npzov33p
  Running command git checkout -b upgrade-python --track origin/upgrade-python
  Resolved https://github.com/Clinical-Genomics/housekeeper to commit 8045080257d306e3e7e2bb9d9692297156b17e1c
  Switched to a new branch 'upgrade-python'
  Installing build dependencies: started
  Branch upgrade-python set up to track remote branch upgrade-python from origin.
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: rich in /home/proj/stage/bin/miniconda3/envs/S_main/bin (from housekeeper==4.8.5) (12.6.0)
Requirement already satisfied: pyyaml in /home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.8/site-packages (from housekeeper==4.8.5) (6.0.1)
Requirement already satisfied: coloredlogs in /home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.8/site-packages (from housekeeper==4.8.5) (15.0.1)
Requirement already satisfied: SQLAlchemy<1.5.0,>=1.3.0 in /home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.8/site-packages (from housekeeper==4.8.5) (1.3.24)
Requirement already satisfied: Click in /home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.8/site-packages (from housekeeper==4.8.5) (6.7)
Requirement already satisfied: marshmallow in /home/proj/stage/bin/miniconda3/envs/S_main/bin (from housekeeper==4.8.5) (3.18.0)
Requirement already satisfied: humanfriendly>=9.1 in /home/proj/stage/bin/miniconda3/envs/S_main/bin (from coloredlogs->housekeeper==4.8.5) (10.0)
Requirement already satisfied: packaging>=17.0 in /home/proj/stage/bin/miniconda3/envs/S_main/bin (from marshmallow->housekeeper==4.8.5) (21.3)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /home/proj/stage/bin/miniconda3/envs/S_main/bin (from rich->housekeeper==4.8.5) (2.13.0)
Requirement already satisfied: typing-extensions<5.0,>=4.0.0 in /home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.8/site-packages (from rich->housekeeper==4.8.5) (4.8.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /home/proj/stage/bin/miniconda3/envs/S_main/bin (from rich->housekeeper==4.8.5) (0.9.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/proj/stage/bin/miniconda3/envs/S_main/bin (from packaging>=17.0->marshmallow->housekeeper==4.8.5) (3.0.9)
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/sebastian.allard
done.
Log deploy... done.
housekeeper, version 4.8.5
```

**Comment by seallard** [comment]
Tested with
```
θ67° [sebastian.allard@hasta:~] [S_base] 6s $ housekeeper get bundle trustyhyena
2023-10-04 15:44:14 hasta.scilifelab.se housekeeper.cli.core[185257] INFO Use root path /home/proj/stage/housekeeper-bundles
                📦 Bundle table 📦                 
┏━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ ID     ┃ Bundle name ┃ Version IDs ┃ Created    ┃
┡━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ 154109 │ trustyhyena │ 158027      │ 2023-10-03 │
└────────┴─────────────┴─────────────┴────────────┘
```

**Review by henrikstranneheim — APPROVED** [review]
Thrilled that this is happening 💯

**Pull request merged**
