### PR TITLE
Docker production image

### PR DESCRIPTION
**Pull request by moonso**
# Summary

- This pr adds a first suggestion to a production ready Docker image

## Dockerfile

The dockerfile is created by trying to follow the best practices from the [docker docs](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/).

**Summary:**

- Use labels to describe the container (Thanks to mip team)
- Reduce the image size as much as possible by using small base image and only include necessary files in the build
- Use locked dependencies for full control of reproducibility
- Avoid running as root in the container for security reasons

## Docker hub

A workflow for building and pushing image to docker-hub is created

## Testing

Run the image by downloading from docker-hub

### How to test
- [x] Run the image with `docker container run --rm clinicalgenomics/housekeeper:3.0.1 --version`

### Expected test outcome
- [x] check that the version is displayed
- [x] Take a screenshot and attach or copy/paste the output.
Skärmavbild 2020-10-23 kl  14 44 27

## Review
- [x] code approved by HS, HFA
- [x] tests executed by MM
- [x] "Merge and deploy" approved by MM
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:

- [x] **MINOR** - when you add functionality in a backwards compatible manner

### CODE REVIEW

**Comment by moonso** [comment]
Container experts! @eriksjolund @henrikstranneheim @hassanfa @jemten could you have a quick look at this one?

**Review by henrikstranneheim — APPROVED** [review]
👍

**Review by hassanfa — APPROVED** [review]
Phenomenal! ⭐

**Comment by hassanfa** [comment]
> Container experts! @eriksjolund @henrikstranneheim @hassanfa @jemten could you have a quick look at this one?

I'm no expert though, just a mere poweruser!

**Review by eriksjolund — APPROVED** [review]
Looks good!

The Github action 
https://github.com/docker/build-push-action/releases/tag/v2.0.0
was released only 3 hours ago.
Cool that we have already start using it!

**Pull request merged**
