### PR TITLE
refactor(moving log info to debug)

### PR DESCRIPTION
**Pull request by ChrOertlin**
# Description

Moving the LOG level from the Housekeeper store handlers to DEBUG. These messages clutter the output when functions are called repeatedly in other scripts.

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
👍

**Review by henrikstranneheim — APPROVED** [review]

**Review by diitaz93 — APPROVED** [review]
👍

**Comment by ChrOertlin** [comment]
# Housekeeper get bundle 
2023-09-29 16:13:00 hasta.scilifelab.se housekeeper.store.api.core[245909] DEBUG Initializing Store
2023-09-29 16:13:00 hasta.scilifelab.se housekeeper.store.api.handlers.read[245909] DEBUG Fetching all bundles
2023-09-29 16:13:00 hasta.scilifelab.se housekeeper.store.api.handlers.read[245909] DEBUG Fetching bundle with name:

**Comment by ChrOertlin** [comment]
stage: repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/proj/production/demultiplexed-runs
done.
Log deploy... done.
housekeeper, version 4.8.3

prod:
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/proj/production/demultiplexed-runs
done.
Log deploy... done.
housekeeper, version 4.8.3

**Pull request merged**
