### PR TITLE
Add jobs to CI build

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
PR that adds CI-build jobs to this repo

**How to test: **
- [x] open the travis build checks

**Expected outcome: **
- [x] Several build jobs built 
- [x] Screenshot

- [x] Reviewed @ingkebil 
- [x] Tested
- [x] merge & deploy OK @ingkebil 

This is a minor bump since we add CI func but we don't add any end user func

### CODE REVIEW

**Comment by ingkebil** [comment]
goddamn astroid

**Comment by patrikgrenfeldt** [comment]
Test results:
image
image
👍

**Comment by ingkebil** [comment]
Looks good! approved

**Comment by patrikgrenfeldt** [comment]
@ingkebil could you please merge and bump?

**Comment by ingkebil** [comment]
done

**Comment by patrikgrenfeldt** [comment]
Thanx!

**Pull request merged**
